services:
  api:
    image: heurekaoc/testday-api:latest
    ports:
      - "5555:5000"

  producer:
    image: heurekaoc/testday-producer:latest
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_VIRTUAL_HOST: "/"
      RABBITMQ_LOGIN: "guest"
      RABBITMQ_PASSWORD: "guest"
      RABBITMQ_EXCHANGE_NAME: "amq.topic"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
