# This workflow will run tests

name: Python Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example

      matching-api:
        image: heurekaoc/testday-api:latest
        ports:
          - 5555:5000

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Run lint and tests
      run: |
        python3 -m venv .heureka.venv
        source .heureka.venv/bin/activate
        python3 -m pip install build
        pip install '.[tests]'
        ruff check
        pytest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build docker image
      uses: docker/build-push-action@v6
      with:
        push: false
        tags: romrak/heureka:latest
        outputs: type=docker,dest=/tmp/heureka.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: heureka-image
        path: /tmp/heureka.tar

