# This workflow will run tests

name: Python Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Run lint and tests
      run: |
        python3 -m venv .heureka.venv
        source .heureka.venv/bin/activate
        python3 -m pip install build
        pip install '.[tests]'
        ruff check
        pytest
